# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 12:19
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cilj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(default='', max_length=150)),
                ('vrednost', models.FloatField()),
                ('trenutno_privarcevano', models.FloatField(default=0)),
                ('od_datuma', models.DateTimeField(default=datetime.datetime.now)),
                ('do_datuma', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='IzdatekPrejemek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(default='', max_length=20)),
                ('opis', models.CharField(default='', max_length=100)),
                ('znesek', models.FloatField()),
                ('kategorija', models.CharField(default='', max_length=30)),
                ('datum', models.DateTimeField(default=datetime.datetime.now)),
                ('banka_denarnica', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stanje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(default='', max_length=20)),
                ('stanje', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transakcija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(default='', max_length=100)),
                ('znesek', models.FloatField()),
                ('smer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Uporabnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uporabnik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transakcija',
            name='uporabnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Uporabnik'),
        ),
        migrations.AddField(
            model_name='stanje',
            name='uporabnik',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='registration.Uporabnik'),
        ),
        migrations.AddField(
            model_name='izdatekprejemek',
            name='stanje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Stanje'),
        ),
        migrations.AddField(
            model_name='cilj',
            name='uporabnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Uporabnik'),
        ),
    ]
