# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20161229_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transakcija',
            name='uporabnik',
        ),
        migrations.DeleteModel(
            name='Transakcija',
        ),
    ]
